CREATE VIEW "HS_HUBSPOT"."PUBLIC"."HUBSPOT_CALL" AS
SELECT C."BODY", C."TITLE",  
DATEADD('MS',E."CREATED_AT",'1970-01-01') AS "CREATED_AT" ,E."CREATED_BY", 
E."ID" AS "UID",  CE."CONTACT_ID",  D."LABEL" AS "CALL_OUTCOME", 
IFF(CON."TOTAL_REVENUE" >0 AND CON."FIRST_DEAL_CREATED_DATE">DATEADD('MS',E."CREATED_AT",'1970-01-01'),1,0)  AS "PRE_CUSTOMER_CALL",
TO_DATE(DATEADD('MS',E."CREATED_AT",'1970-01-01')) AS "CREATED_AT_DATE",TO_TIME(DATEADD('MS',E."CREATED_AT",'1970-01-01')) AS "CREATED_AT_TIME"
FROM "HS_HUBSPOT"."PUBLIC"."HS_ENGAGEMENT_CALL" C 
LEFT JOIN "HS_HUBSPOT"."PUBLIC"."HS_ENGAGEMENTS" E
ON C."ENGAGEMENT_ID"=E."ID"
LEFT JOIN "HS_HUBSPOT"."PUBLIC"."HS_CONTACT_ENGAGEMENT_ASSOCIATION" CE
ON CE."ENGAGEMENT_ID"=E."ID" 
LEFT JOIN "HS_HUBSPOT"."PUBLIC"."HS_CALL_DISPOSITIONS" D
ON C."DISPOSITION"=D."ID"
LEFT JOIN "HS_HUBSPOT"."PUBLIC"."HS_CONTACTS" CON ON 
CON."ID"=CE."CONTACT_ID"


CREATE VIEW "HS_HUBSPOT"."PUBLIC"."HUBSPOT_EMAIL" AS
SELECT EM."HTML", EM."FROM_EMAIL",EM."SENDER_EMAIL",EM."SUBJECT", EM."TEXT", EM."STATUS", EM."FROM_FIRST_NAME", EM."FROM_LAST_NAME", 
DATEADD('MS',E."CREATED_AT",'1970-01-01') AS "CREATED_AT" ,E."CREATED_BY", E."UID", CE."CONTACT_ID" , 
IFF(CON."TOTAL_REVENUE" >0 AND CON."FIRST_DEAL_CREATED_DATE">DATEADD('MS',E."CREATED_AT",'1970-01-01'),1,0)  AS "PRE_CUSTOMER_EMAIL",
TO_DATE(DATEADD('MS',E."CREATED_AT",'1970-01-01')) AS "CREATED_AT_DATE",TO_TIME(DATEADD('MS',E."CREATED_AT",'1970-01-01')) AS "CREATED_AT_TIME"
FROM "HS_HUBSPOT"."PUBLIC"."HS_ENGAGEMENT_EMAIL" EM 
LEFT JOIN "HS_HUBSPOT"."PUBLIC"."HS_ENGAGEMENTS" E
ON EM."ENGAGEMENT_ID"=E."ID"
LEFT JOIN "HS_HUBSPOT"."PUBLIC"."HS_CONTACT_ENGAGEMENT_ASSOCIATION" CE
ON CE."ENGAGEMENT_ID"=E."ID"
LEFT JOIN "HS_HUBSPOT"."PUBLIC"."HS_CONTACTS" CON ON 
CON."ID"=CE."CONTACT_ID"


CREATE VIEW "HS_HUBSPOT"."PUBLIC"."HUBSPOT_CONTACTS" AS
SELECT "ID","ARCHIVED", "HS_TIME_TO_FIRST_ENGAGEMENT", "CREATEDATE", 
 "HS_LAST_SALES_ACTIVITY_DATE",
 "HS_EMAIL_LAST_SEND_DATE",  "HS_COUNT_IS_WORKED",
"LASTNAME",
 "HS_SA_FIRST_ENGAGEMENT_DATE",
 "HS_SA_FIRST_ENGAGEMENT_OBJECT_TYPE","HS_IS_UNWORKED", 
 "FIRSTNAME","HS_ANALYTICS_NUM_VISITS",
 "HS_SOCIAL_LINKEDIN_CLICKS","HS_ANALYTICS_SOURCE",
 "EMAIL","JOBTITLE",
 "HS_SOCIAL_GOOGLE_PLUS_CLICKS",  "HS_SOCIAL_FACEBOOK_CLICKS",
 "HS_SOCIAL_TWITTER_CLICKS", "LIFECYCLESTAGE", "HS_EMAIL_SENDS_SINCE_LAST_ENGAGEMENT",
 "HS_COUNT_IS_UNWORKED", "MOBILEPHONE", "STATE", "PHONE",  "HS_EMAIL_LAST_OPEN_DATE",
 "ZIP", "CITY", "COUNTRY", "HS_EMAIL_LAST_CLICK_DATE","HS_EMAIL_FIRST_CLICK_DATE",
 "HS_SEQUENCES_ENROLLED_COUNT","HS_SEQUENCES_IS_ENROLLED", "HS_SEQUENCES_ACTIVELY_ENROLLED_COUNT",
 "HS_LATEST_SEQUENCE_ENDED_DATE","SENIORITY",
 "FIRST_DEAL_CREATED_DATE", "NUM_ASSOCIATED_DEALS", "HS_TIME_BETWEEN_CONTACT_CREATION_AND_DEAL_CREATION",
 "DAYS_TO_CLOSE", "HS_TIME_BETWEEN_CONTACT_CREATION_AND_DEAL_CLOSE", "CLOSEDATE",
 "TOTAL_REVENUE", "HS_EMAIL_LAST_REPLY_DATE", "FIRST_CONVERSION_EVENT_NAME", "FIRST_CONVERSION_DATE",
 "CURRENTLYINWORKFLOW","HS_ANALYTICS_FIRST_URL","HS_ANALYTICS_LAST_URL", "HS_ANALYTICS_FIRST_REFERRER", "HS_ANALYTICS_LAST_REFERRER",
 TO_DATE("CREATEDATE") AS  "CREATED_AT_DATE",TO_TIME("CREATEDATE") AS  "CREATED_AT_TIME"
   FROM "HS_HUBSPOT"."PUBLIC"."HS_CONTACTS"


CREATE VIEW "HS_HUBSPOT"."PUBLIC"."HUBSPOT_COMPANIES" AS
SELECT "ID", "INDUSTRY", "CITY","NUMBEROFEMPLOYEES", "HS_NUM_OPEN_DEALS", "STATE", "NAME", "TOTAL_REVENUE", 
"CREATED_AT", "ARCHIVED", "COUNTRY", "CREATEDATE", "HS_ANALYTICS_SOURCE", "ZIP", "WEBSITE",TO_DATE("CREATEDATE") AS  "CREATED_AT_DATE",
TO_TIME("CREATEDATE") AS  "CREATED_AT_TIME"
FROM "HS_HUBSPOT"."PUBLIC"."HS_COMPANIES"


CREATE VIEW "HS_HUBSPOT"."PUBLIC"."HUBSPOT_COMPANY_CONTACT" AS
SELECT "CONTACT_ID", "COMPANY_ID", "TYPE" FROM "HS_HUBSPOT"."PUBLIC"."HS_CONTACT_COMPANY_ASSOCIATION"


CREATE VIEW "HS_HUBSPOT"."PUBLIC"."HUBSPOT_MEETING" AS
SELECT DATEADD('MS',M."START_TIME",'1970-01-01') AS "START_TIME", DATEADD('MS',M."END_TIME",'1970-01-01') AS "END_TIME",
M."TITLE", M."BODY", M."MEETING_OUTCOME",M."LOCATION", 
DATEADD('MS',E."CREATED_AT",'1970-01-01') AS "CREATED_AT" ,E."CREATED_BY", E."UID", CE."CONTACT_ID",
IFF(CON."TOTAL_REVENUE" >0 AND CON."FIRST_DEAL_CREATED_DATE">DATEADD('MS',E."CREATED_AT",'1970-01-01'),1,0)  AS "PRE_CUSTOMER_MEET",
TO_DATE(DATEADD('MS',M."START_TIME",'1970-01-01')) AS "MEETING_DATE",TO_TIME(DATEADD('MS',M."START_TIME",'1970-01-01')) AS "MEETING_TIME"
FROM "HS_HUBSPOT"."PUBLIC"."HS_ENGAGEMENT_MEETING" M 
LEFT JOIN "HS_HUBSPOT"."PUBLIC"."HS_ENGAGEMENTS" E
ON M."ENGAGEMENT_ID"=E."ID"
LEFT JOIN "HS_HUBSPOT"."PUBLIC"."HS_CONTACT_ENGAGEMENT_ASSOCIATION" CE
ON CE."ENGAGEMENT_ID"=E."ID"
LEFT JOIN "HS_HUBSPOT"."PUBLIC"."HS_CONTACTS" CON ON 
CON."ID"=CE."CONTACT_ID"


CREATE VIEW "HS_HUBSPOT"."PUBLIC"."HUBSPOT_MARKETING_EMAIL_TEMP" AS
select to_varchar(t0.value:"absoluteUrl") AS "EMAIL_URL", DATEADD('MS',to_varchar(t0.value:"created"),'1970-01-01')  AS "DATE_CREATED", 
to_varchar(t0.value:"fromName") AS "EMAIL_FROM_NAME", to_varchar(t0.value:"name") AS "CAMPAIGN_NAME", 
to_varchar(t0.value:"replyTo") AS "REPLY_TO_EMAIL", to_number(t0.value:"stats"."counters"."bounce") AS "BOUNCE", 
to_number(t0.value:"stats"."counters"."click") AS "CLICK", to_number(t0.value:"stats"."counters"."contactslost") AS "CONTACTS_LOST",
to_number(t0.value:"stats"."counters"."delivered") AS "DELIVERED", to_number(t0.value:"stats"."counters"."open") AS "OPEN",
to_number(t0.value:"stats"."counters"."reply") AS "REPLY", to_number(t0.value:"stats"."counters"."sent") AS "SENT",  
to_number(t0.value:"stats"."counters"."unsubscribed") AS "UNSUBSCRIBED", to_number(t0.value:"stats"."ratios"."bounceratio") AS "BOUNCE_RATIO",
to_double(t0.value:"stats"."ratios"."clickratio") AS "CLICK_RATIO", to_double(t0.value:"stats"."ratios"."clickthroughratio") AS "CLICK_THROUGH_RATIO",
to_double(t0.value:"stats"."ratios"."openratio") AS "OPEN_RATIO",to_varchar(t0.value:"subject") AS "EMAIL_SUBJECT", to_number(t1.value) AS "CAMPAIGN_ID" 
from "HS_HUBSPOT"."PUBLIC"."HS_MARKETING_EMAILS", lateral flatten (input => "OBJECTS") as t0,
lateral flatten (input => t0.value:"allEmailCampaignIds") as t1


CREATE VIEW "HS_HUBSPOT"."PUBLIC"."HUBSPOT_MARKETING_CAMPAIGN_SENT_DATE" AS
SELECT "CAMPAIGN_ID",min ("CREATED") AS "DATE_CAMPAIGN_SENT" FROM "HS_HUBSPOT"."PUBLIC"."HUBSPOT_MARKETING_EMAIL_TEMP" t LEFT JOIN "HS_HUBSPOT"."PUBLIC"."HUBSPOT_MARKETING_EMAIL_EVENTS" ev 
ON t."CAMPAIGN_ID"=ev."EMAIL_CAMPAIGN_ID" GROUP BY "CAMPAIGN_ID"

CREATE VIEW "HS_HUBSPOT"."PUBLIC"."HUBSPOT_MARKETING_EMAIL" AS
SELECT t.*,s."DATE_CAMPAIGN_SENT",TO_DATE(s."DATE_CAMPAIGN_SENT") AS "CAMPAIGN_DATE",TO_TIME(s."DATE_CAMPAIGN_SENT") AS "CAMPAIGN_TIME"
FROM "HS_HUBSPOT"."PUBLIC"."HUBSPOT_MARKETING_EMAIL_TEMP" t LEFT JOIN "HS_HUBSPOT"."PUBLIC"."HUBSPOT_MARKETING_CAMPAIGN_SENT_DATE" s 
ON t."CAMPAIGN_ID"=s."CAMPAIGN_ID" 


CREATE VIEW "HS_HUBSPOT"."PUBLIC"."HUBSPOT_MARKETING_EMAIL_EVENTS" AS
SELECT E."APP_ID",E."APP_NAME", DATEADD('MS',E."CREATED",'1970-01-01') AS "CREATED", E."EMAIL_CAMPAIGN_ID", E."ID", E."PORTAL_ID",
E."RECIPIENT", E."TYPE", DATEADD('MS',E."SENT_BY_CREATED",'1970-01-01') AS "SENT_BY_CREATED", E."SENT_BY_ID", E."BROWSER_NAME", E."LOCATION_CITY",
E."LOCATION_COUNTRY", E."LOCATION_STATE", E."USER_AGENT", E."DURATION", E."SOURCE", E."PORTAL_SUBSCRIPTION_STATUS",
E."ATTEMPT", E."RESPONSE",E."URL", E."SUBJECT", E."FROM" AS "FROM_EMAIL",
E."DROP_MESSAGE", E."CAUSED_BY_ID",
IFF(CON."TOTAL_REVENUE" >0 AND E.TYPE='SENT' AND CON."FIRST_DEAL_CREATED_DATE">DATEADD('MS',E."CREATED",'1970-01-01'),1,0)  AS "PRE_CUSTOMER_MARKETING_EMAIL",
TO_DATE(DATEADD('MS',E."CREATED",'1970-01-01')) AS "CREATED_AT_DATE", TO_TIME(DATEADD('MS',E."CREATED",'1970-01-01')) AS "CREATED_AT_TIME"
FROM "HS_HUBSPOT"."PUBLIC"."HS_EMAIL_EVENTS" E
LEFT JOIN "HS_HUBSPOT"."PUBLIC"."HS_CONTACTS" CON 
ON E."RECIPIENT"=CON."EMAIL"


CREATE VIEW "HS_HUBSPOT"."PUBLIC"."HUBSPOT_DEALS" AS
SELECT D."ID", D."DEALNAME",
D."HS_FORECAST_AMOUNT",D."CREATEDATE",D."HS_IS_CLOSED",D."HS_DEAL_STAGE_PROBABILITY", D."DAYS_TO_CLOSE",
D."HS_CREATED_BY_USER_ID", D."HS_PROJECTED_AMOUNT", D."HS_IS_CLOSED_WON",D."HS_CLOSED_AMOUNT_IN_HOME_CURRENCY",
D."DESCRIPTION", D."AMOUNT_IN_HOME_CURRENCY",D."HS_CLOSED_AMOUNT",D."CLOSEDATE",D."DEALTYPE",D."AMOUNT",D."HS_LASTMODIFIEDDATE",
D."PIPELINE" , PS."LABEL" AS "DEALSTAGE", PS."DISPLAY_ORDER" AS "PIPELINE_DISPLAY_ORDER", D."HS_DATE_ENTERED_CLOSEDWON",
TO_DATE(D."CREATEDATE") AS "CREATED_AT_DATE",TO_TIME(D."CREATEDATE") AS "CREATED_AT_TIME"
FROM "HS_HUBSPOT"."PUBLIC"."HS_DEALS" D
LEFT JOIN "HS_HUBSPOT"."PUBLIC"."HS_DEALS_PIPELINE_STAGES" PS 
ON D."PIPELINE" = PS."PIPELINE_ID" AND D."DEALSTAGE"=PS."ID"


CREATE VIEW "HS_HUBSPOT"."PUBLIC"."HUBSPOT_DEAL_COMPANY" AS
SELECT "DEAL_ID","COMPANY_ID" FROM "HS_HUBSPOT"."PUBLIC"."HS_DEAL_COMPANY_ASSOCIATION"

CREATE VIEW "HS_HUBSPOT"."PUBLIC"."HUBSPOT_DEAL_CONTACT" AS
SELECT "DEAL_ID","CONTACT_ID" FROM "HS_HUBSPOT"."PUBLIC"."HS_DEAL_CONTACT_ASSOCIATION"

CREATE VIEW "HS_HUBSPOT"."PUBLIC"."HUBSPOT_FORMS" AS
SELECT "GUID","NAME" AS "FORM_NAME", "ACTION", "SUBMIT_TEXT", "LEAD_NURTURING_CAMPAIGN_ID" FROM "HS_HUBSPOT"."PUBLIC"."HS_FORMS"


CREATE VIEW "HS_HUBSPOT"."PUBLIC"."HUBSPOT_CONTACT_FORM_SUBMISSION" AS
SELECT DATEADD('MS',F."SUBMITTED_AT",'1970-01-01') AS "SUBMITTED_AT", F."FORM_ID", F."CONTACT_ID",
IFF(CON."TOTAL_REVENUE" >0 AND CON."FIRST_DEAL_CREATED_DATE">DATEADD('MS',F."SUBMITTED_AT",'1970-01-01'),1,0)  AS "PRE_CUSTOMER_FORM",
TO_DATE(DATEADD('MS',F."SUBMITTED_AT",'1970-01-01')) AS "CREATED_AT_DATE",TO_TIME(DATEADD('MS',F."SUBMITTED_AT",'1970-01-01')) AS "CREATED_AT_TIME"
FROM "HS_HUBSPOT"."PUBLIC"."HS_CONTACT_FORM_SUBMISSION" F
LEFT JOIN "HS_HUBSPOT"."PUBLIC"."HS_CONTACTS" CON ON 
CON."ID"=F."CONTACT_ID"

CREATE VIEW "HS_HUBSPOT"."PUBLIC"."HUBSPOT_OWNER" AS
SELECT "ID", "EMAIL", "FIRST_NAME", "LAST_NAME","USER_ID", "ARCHIVED"
   FROM "HS_HUBSPOT"."PUBLIC"."HS_OWNERS";


